SHELL := /bin/bash

mpi_info = $(shell $(MPICC) -show)
compiler = $(notdir $(firstword $(mpi_info)))
$(info Found [$(compiler)])

###############################################################################
# Compilation and linking options

ifeq "$(ap)" "float"
        CUBISMZFLAGS += -D_FLOAT_PRECISION_
endif

ifeq "$(config)" "release"
	CUBISMZFLAGS += -DNDEBUG -O3
else
	CUBISMZFLAGS += -g
endif

ifeq "$(omp)" "1"
	ifneq "$(compiler)" "clang++"
		CUBISMZFLAGS += -fopenmp
	endif
endif

CUBISMZFLAGS += -D_BLOCKSIZE_=$(bs) -D_BLOCKSIZEX_=$(bs) -D_BLOCKSIZEY_=$(bs) -D_BLOCKSIZEZ_=$(bs)
CUBISMZFLAGS += -I../Compressor/Cubism/source/ -I../Compressor/source/

CUBISMZFLAGS += -I$(hdf-inc) -D_USE_HDF_
CUBISMZLIBS += -L$(hdf-lib) $(hdf-libraries)
CUBISMZLIBS += -lm

# ThirdParty libraries
CUBISMZFLAGS += -I../ThirdParty/build/include
CUBISMZLIBS += -L../ThirdParty/build/lib


CUBISMZFLAGS += $(extra)

###############################################################################
# Flags related to the compression options

ifeq "$(wavz)" "1"
       CUBISMZFLAGS += -D_USE_WAVZ_
endif

ifeq "$(fpzip)" "1"
	CUBISMZFLAGS += -D_USE_FPZIP_  -I../ThirdParty/build/include/fpzip
	CUBISMZLIBS += -lfpzip
endif

ifeq "$(zfp)" "1"
	CUBISMZFLAGS += -D_USE_ZFP_  -I../ThirdParty/build/include/zfp
	CUBISMZLIBS += -lzfp
endif

ifeq "$(sz)" "1"
	CUBISMZFLAGS += -D_USE_SZ_  -I../ThirdParty/build/include
	CUBISMZLIBS += -lSZ  -lzlib
	needs_lz = 0
endif


###############################################################################
# Flags related to the encoding options

ifeq "$(zlib)" "1"
	CUBISMZFLAGS += -D_USE_ZLIB_
	CUBISMZLIBS += -lz
endif

ifeq "$(lz4)" "1"
       CUBISMZFLAGS += -D_USE_LZ4_  -I../ThirdParty/build/include/lz4
       CUBISMZLIBS += -llz4
endif

ifeq "$(needs_lz)" "1"
	CUBISMZLIBS += -lz
endif

###############################################################################
# Flags related to the extensions to the wavelet-based compression (wavz)

ifeq "$(shuffle3)" "1"
       CUBISMZFLAGS += -D_USE_SHUFFLE3_
endif

ifeq "$(zerobits)" "4"
       CUBISMZFLAGS += -D_USE_ZEROBITS_
       CUBISMZFLAGS += -D_ZEROBITS_=4
endif
ifeq "$(zerobits)" "8"
       CUBISMZFLAGS += -D_USE_ZEROBITS_
       CUBISMZFLAGS += -D_ZEROBITS_=8
endif
ifeq "$(zerobits)" "12"
       CUBISMZFLAGS += -D_USE_ZEROBITS_
       CUBISMZFLAGS += -D_ZEROBITS_=12
endif
ifeq "$(zerobits)" "16"
       CUBISMZFLAGS += -D_USE_ZEROBITS_
       CUBISMZFLAGS += -D_ZEROBITS_=16
endif
