SHELL := /bin/bash

mpi_info = $(shell $(MPICXX) -show)
compiler = $(notdir $(firstword $(mpi_info)))
$(info Found [$(compiler)])

###############################################################################
# Compilation and linking options

ifeq "$(ap)" "float"
        CUBISMZFLAGS += -D_FLOAT_PRECISION_
endif

ifeq "$(config)" "release"
	CUBISMZFLAGS += -DNDEBUG -O3
else
	CUBISMZFLAGS += -g
endif

ifeq "$(omp)" "1"
	ifneq "$(compiler)" "clang++"
		CUBISMZFLAGS += -fopenmp
	endif
endif

CUBISMZFLAGS += -D_BLOCKSIZE_=$(bs) -D_BLOCKSIZEX_=$(bs) -D_BLOCKSIZEY_=$(bs) -D_BLOCKSIZEZ_=$(bs)
CUBISMZFLAGS += -I../Compressor/Cubism/source/ -I../Compressor/source/

CUBISMZFLAGS += -I$(hdf-incdir) -D_USE_HDF_
CUBISMZLIBS += -L$(hdf-libdir) $(hdf-libs)
CUBISMZLIBS += -lm

# ThirdParty libraries
CUBISMZFLAGS += -I../ThirdParty/build/include
CUBISMZLIBS += -L../ThirdParty/build/lib


CUBISMZFLAGS += $(extra)

###############################################################################
# Main rules
all: tools

tools: thirdparty-libs tools-only

tools-only:
	$(MAKE) -C Tools/ install dir=default
	$(MAKE) -C Tools/ install dir=wavz_zlib wavz=1 zlib=1
	$(MAKE) -C Tools/ install dir=fpzip fpzip=1
	$(MAKE) -C Tools/ install dir=zfp zfp=1
	$(MAKE) -C Tools/ install dir=sz sz=1

tools-custom:
	$(MAKE) -C Tools/ install

thirdparty-libs:
	$(MAKE) -C ThirdParty/

clean:
	$(MAKE) -C Tools/ clean
	$(MAKE) -C ThirdParty/ clean
