SHELL := /bin/bash

CC ?= mpic++
cc ?= mpicc
LD ?= mpic++

###############################################################################
hdf-inc ?= .
hdf-lib ?= .

###############################################################################
# User options

# general software configuration options
bs ?= 32
ap ?= float
omp ?= 1
align ?= 16
needs_lz ?= 1

# options for the first compression stage (floating point)
wavz ?= 0
fpzip ?= 0
zfp ?= 0
sz ?= 0

# options for the second compression stage (encoding)
zlib ?= 0
lz4 ?= 0

# options (bit zeroing, byte shuffling) for the wavelet coefficients, applied between the first and second stage
zerobits ?= 0	# for wavz + zerobits
shuffle3 ?= 0	# for wavz + shuffle3

###############################################################################
# Compilation and linking options

ifeq "$(ap)" "float"
        CPPFLAGS += -D_FLOAT_PRECISION_
endif

ifeq "$(config)" "release"
	OPTFLAGS+= -DNDEBUG -O3 
else
	CPPFLAGS += -g
endif

ifeq "$(omp)" "1"
	CPPFLAGS += -fopenmp
	OPTFLAGS += -fopenmp
endif

CPPFLAGS += -D_ALIGNBYTES_=$(align) -D_BLOCKSIZE_=$(bs) -D_BLOCKSIZEX_=$(bs) -D_BLOCKSIZEY_=$(bs) -D_BLOCKSIZEZ_=$(bs)
CPPFLAGS += -I../Compressor/Cubism/source/ -I../Compressor/source/

CPPFLAGS += -I$(hdf-inc) -D_USE_HDF_
LIBS += -L$(hdf-lib) -lhdf5
LIBS += -lm

# ThirdParty libraries
LIBS += -L../ThirdParty/build/lib


CPPFLAGS += $(extra)

###############################################################################
# Flags related to the compression options

ifeq "$(wavz)" "1"
       CPPFLAGS += -D_USE_WAVZ_
endif

ifeq "$(fpzip)" "1"
	CPPFLAGS += -D_USE_FPZIP_  -I../ThirdParty/build/include/fpzip
	LIBS += -lfpzip
endif

ifeq "$(zfp)" "1"
	CPPFLAGS += -D_USE_ZFP_  -I../ThirdParty/build/include/zfp
	LIBS += -lzfp
endif

ifeq "$(sz)" "1"
	CPPFLAGS += -D_USE_SZ_  -I../ThirdParty/build/include
	LIBS += -lSZ  -lzlib
	needs_lz = 0
endif


###############################################################################
# Flags related to the encoding options

ifeq "$(zlib)" "1"
       CPPFLAGS += -D_USE_ZLIB_
       LIBS +=  -lz
endif

ifeq "$(lz4)" "1"
       CPPFLAGS += -D_USE_LZ4_  -I../ThirdParty/build/include/lz4
       LIBS += -llz4
endif

ifeq "$(needs_lz)" "1"
	LIBS += -lz
endif

###############################################################################
# Flags related to the extensions to the wavelet-based compression (wavz)

ifeq "$(shuffle3)" "1"
       CPPFLAGS += -D_USE_SHUFFLE3_
endif

ifeq "$(zerobits)" "4"
       CPPFLAGS += -D_USE_ZEROBITS_
       CPPFLAGS += -D_ZEROBITS_=4
endif
ifeq "$(zerobits)" "8"
       CPPFLAGS += -D_USE_ZEROBITS_
       CPPFLAGS += -D_ZEROBITS_=8
endif
ifeq "$(zerobits)" "12"
       CPPFLAGS += -D_USE_ZEROBITS_
       CPPFLAGS += -D_ZEROBITS_=12
endif
ifeq "$(zerobits)" "16"
       CPPFLAGS += -D_USE_ZEROBITS_
       CPPFLAGS += -D_ZEROBITS_=16
endif
