# Makefile
# CubismZ
#
# Copyright 2018 ETH Zurich. All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
.PHONY: clean

clean:
	find . -name "*.cz" -exec rm -f {} \;
	find . -name "*.h5" -exec rm -f {} \;
	find . -name "*.xmf" -exec rm -f {} \;
	find . -name "run_all.txt" -exec rm -f {} \;
