SHELL := /bin/bash

CC ?= gcc
LD ?= gcc

# core
bs ?= 32
ap ?= float
omp ?= 1
align ?= 16
qpx ?= 0
qpxemu ?= 0

# +node
hdf ?= 0

needs_lz ?= 1

#compression stage-1 (floating point)
wavz ?= 0

fpzip ?= 0
shuffle ?= 0
zerobits ?= 0
zfp ?= 0
sz ?= 0

#compression stage-2 (encoding)
zlib ?= 0
lz4 ?= 0

###############################################################################

ifeq "$(sz)" "1"
needs_lz = 0
endif

###############################################################################

CPPFLAGS+= $(extra)

ifeq "$(ap)" "float"
        CPPFLAGS += -D_FLOAT_PRECISION_
endif

CPPFLAGS += -D_MICROFUSION_=$(microfusion)

ifeq "$(config)" "release"
	ifeq "$(CC)" "icc"
		OPTFLAGS+= -DNDEBUG -O3 -xHOST  -ip -ansi-alias -fno-fnalias -inline-level=1
		ifeq "$(ap)" "float"
			CPPFLAGS += -fp-model precise
		else
			CPPFLAGS += -fast
		endif
	else
		OPTFLAGS += -O3 -fno-expensive-optimizations -falign-functions=16 -DNDEBUG 
		OPTFLAGS += -DNDEBUG
	endif
else
	CPPFLAGS += -g
endif

ifeq "$(ap)" "float"
	CPPFLAGS += -D_SP_COMP_
endif

ifeq "$(qpx)" "1"
	CPPFLAGS += -D_QPX_
endif

ifeq "$(qpxemu)" "1"
	CPPFLAGS += -D_QPXEMU_ -msse -msse2
endif

ifeq "$(omp)" "1"
	ifeq "$(CC)" "icc"
		CPPFLAGS += -openmp
		OPTFLAGS += -openmp
	else
		CPPFLAGS += -fopenmp
		OPTFLAGS += -fopenmp
	endif
endif

###############################################################################

hdf-inc ?=.
hdf-lib ?=.

###############################################################################
# Testing machines

ifneq "$(findstring falcon,$(shell hostname))" ""
	hdf-inc = /opt/hdf5_mpich/include
	hdf-lib = /opt/hdf5_mpich/lib
endif
###############################################################################

CPPFLAGS += -D_ALIGNBYTES_=$(align) -D_BLOCKSIZE_=$(bs) -D_BLOCKSIZEX_=$(bs) -D_BLOCKSIZEY_=$(bs) -D_BLOCKSIZEZ_=$(bs) 
CPPFLAGS += -I../../../Cubism/source/ -I../source -I../../Compressor/source/ -I/usr/local/include/
CPPFLAGS += -I../../../../Cubism/source

ifeq "$(hdf)" "1"
	CPPFLAGS += -I$(hdf-inc) -D_USE_HDF_
	LIBS += -L$(hdf-lib) -lhdf5
endif

CPPFLAGS +=  -I$(hdf-inc)

LIBS += -lstdc++ -lm

ifeq "$(needs_lz)" "1"
LIBS += -lz
endif

###############################################################################
# Compression Options

# ThirdParty libraries
LIBS += -L../../ThirdParty/build/lib

ifeq "$(wavz)" "1"
       CPPFLAGS += -D_USE_WAVZ_
endif

ifeq "$(fpzip)" "1"
	CPPFLAGS += -D_USE_FPZIP_  -I../../ThirdParty/build/include/fpzip
	LIBS += -lfpzip
endif

ifeq "$(zfp)" "1"
	CPPFLAGS += -D_USE_ZFP_  -I../../ThirdParty/build/include/zfp
	LIBS += -lzfp
endif

ifeq "$(sz)" "1"
	CPPFLAGS += -D_USE_SZ_  -I../../ThirdParty/build/include
	LIBS += -lSZ  -lzlib

#	CPPFLAGS += -D_USE_SZ_  -I../../ThirdParty/build/include
#       LIBS += ../../ThirdParty/build/lib/libSZ.a ../../ThirdParty/build/lib/libzlib.a
endif

ifeq "$(shuffle)" "1"
       CPPFLAGS += -D_USE_SHUFFLE_
endif

ifeq "$(zerobits)" "4"
       CPPFLAGS += -D_USE_ZEROBITS_
       CPPFLAGS += -D_ZEROBITS_=4
endif
ifeq "$(zerobits)" "8"
       CPPFLAGS += -D_USE_ZEROBITS_
       CPPFLAGS += -D_ZEROBITS_=8
endif
ifeq "$(zerobits)" "12"
       CPPFLAGS += -D_USE_ZEROBITS_
       CPPFLAGS += -D_ZEROBITS_=12
endif
ifeq "$(zerobits)" "16"
       CPPFLAGS += -D_USE_ZEROBITS_
       CPPFLAGS += -D_ZEROBITS_=16
endif

###############################################################################
# Encoding Options

ifeq "$(zlib)" "1"
       CPPFLAGS += -D_USE_ZLIB_
       LIBS +=  -lz
endif

ifeq "$(lz4)" "1"
       CPPFLAGS += -D_USE_LZ4_  -I../../ThirdParty/build/include/lz4
       LIBS += -llz4
endif

# Extensions to the Wavelet-based Compression (wavz)

ifeq "$(shuffle3)" "1"
       CPPFLAGS += -D_USE_SHUFFLE3_
endif
