#!/usr/bin/env bash
# File       : make_sz
# Created    : Fri Jul 21 2017 03:46:12 PM (+0200)
# Author     : Fabian Wermelinger
# Description: Build sz library
# Copyright 2017 ETH Zurich. All Rights Reserved.
CWD="$(pwd -P)"
mkdir -p build

# SZ
git clone https://github.com/disheng222/SZ.git src
cd src
./configure --prefix=${CWD}/build --enable-static
make -j4
make install
make clean
